// Physical UDP payloads captured read-only from a RoboSense Airy on 2026-09-23.
// DIFOP network addresses, MAC, and serial are redacted to test identities.
// Replay is loopback-only and does not contact the LiDAR.
use carvi_rsd::{Driver, DriverConfig, InputType, LidarType};
use std::{
    net::UdpSocket,
    thread,
    time::{Duration, Instant},
};

const MSOP_B64: &str = "VaoFWgAAAAB+Ha7OAADa7wAAAAUAAAAA5q8AAZkqADECAAAAAACjKX4L/+4CRQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/uAkUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7gJtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+4CbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/uApUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7gKVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+4CvQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/uAr0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAA";
const DIFOP_B64: &str = "pf8AWhERVVUCWMAAAgHAAAICAgAAAAABGisAAB5sAAAAAIygAAAAAAAQBA8SABADBgAAJQQoEgAlAhQUAAAAAAD///8AwKgBAQEAAAAAAAAEAAAAAAAAAAAFARQAAAABkOYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAA8GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAFRFU1QwMXapAAMAAAAAAOavAAKSNwAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAj3AAAAAAAAAAAAAT4AAAAAAAEaIAMBAQAAAAAAAAAAAAJYAAAk+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVAAB8AADcAAEsAAGcAAIAAAJiAAKwAAMhAAOBAAPiAAQyAASeAAT+AAVaAAWwAAYTAAZvAAbNAAcoAAeJAAfjAAhAAAidAAj0AAlRAAmtAAoFAAplAArBAAseAAt4AAvWAAwvAAyJAAzlAA1FAA2gAA37AA5UAA6yAA8NAA9nAA/CABAiABB4ABDTABEtABGDABHcABI2ABKTABLzABNIABOiABP9ABRkABSzABUNABVpABXSABYoABaDABbfABdGABeVABfxABhOABi9ABkGABlhABm+ABoZABpuABrMABspABuRABvjABxBAByhAB0RAB1dAB27AB4ZAB6NAB7bAB8+AB+aACAPACBYACC+ACEbACGSACHdACJDACKjAQCjAQCnAQCpAQCsAQCuAQCxAQCzAQC2AQC4AQC7AQC9AQC/AACCAACCAACDAACEAACFAACGAACGAACIAACJAACKAACLAACNAQC1AQC3AQC6AQC7AQC+AQDAAQDCAQDEAQDHAQDJAQDLAQDNAACfAACgAACiAACjAACkAACmAACoAACqAACsAACuAACxAAC0AQD3AQD5AQD8AQD/AQEBAQEEAQEHAQEJAQEMAQEZAQElAQEpAADWAADZAADeAADiAADmAADqAADvAAD1AAD7AAECAAEIAAEQAQH5AQIxAQJDAQJXAQJsAQKFAQKfAQK9AQLfAQMHAQMzAQNmAAHZAAH9AAIoAAJdAAKfAAL2AANnAAQOAAUNAAYNAAkwAA2wBNIBgAFKAAAAAABtAAD3nwFLCdkAAAR0BL8AUgBlADwipwAA91ggkSDBG7sAAAKxvzTxDz81GMa6kZgiOS56/DuLQ5Y7iPhiu5IlMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/w";

fn decode_base64(input: &str) -> Vec<u8> {
    let mut out = Vec::new();
    let mut bits = 0u32;
    let mut count = 0u8;
    for byte in input.bytes() {
        if byte == b'=' {
            break;
        }
        let value = match byte {
            b'A'..=b'Z' => byte - b'A',
            b'a'..=b'z' => byte - b'a' + 26,
            b'0'..=b'9' => byte - b'0' + 52,
            b'+' => 62,
            b'/' => 63,
            _ => panic!("invalid base64 fixture"),
        };
        bits = (bits << 6) | u32::from(value);
        count += 6;
        if count >= 8 {
            count -= 8;
            out.push((bits >> count) as u8);
            bits &= (1 << count) - 1;
        }
    }
    out
}

#[test]
fn captured_airy_difop_enables_device_info_after_msop_alone_does_not() {
    let msop = decode_base64(MSOP_B64);
    let difop = decode_base64(DIFOP_B64);
    assert_eq!(msop.len(), 1248);
    assert_eq!(difop.len(), 1248);
    assert_eq!(&msop[..4], &[0x55, 0xaa, 0x05, 0x5a]);
    assert_eq!(
        &difop[..8],
        &[0xa5, 0xff, 0x00, 0x5a, 0x11, 0x11, 0x55, 0x55]
    );
    assert_eq!(&difop[292..298], b"TEST01");

    let msop_receiver = UdpSocket::bind("127.0.0.1:0").unwrap();
    let msop_port = msop_receiver.local_addr().unwrap().port();
    let difop_receiver = UdpSocket::bind("127.0.0.1:0").unwrap();
    let difop_port = difop_receiver.local_addr().unwrap().port();
    drop(msop_receiver);
    drop(difop_receiver);

    let mut config = DriverConfig::new();
    config
        .lidar_type(LidarType::RSAIRY)
        .input_type(InputType::ONLINE_LIDAR);
    {
        let mut input = config.input();
        input.host_address("127.0.0.1");
        input.group_address("0.0.0.0");
        input.msop_port(msop_port);
        input.difop_port(difop_port);
    }
    config.decoder().wait_for_difop(true);
    let mut driver = Driver::new().unwrap();
    driver.init(&config).unwrap();
    driver.start().unwrap();

    let sender = UdpSocket::bind("127.0.0.1:0").unwrap();
    sender.send_to(&msop, ("127.0.0.1", msop_port)).unwrap();
    thread::sleep(Duration::from_millis(100));
    assert!(
        driver.get_device_info().is_err(),
        "MSOP alone must not establish DIFOP identity"
    );

    let deadline = Instant::now() + Duration::from_secs(3);
    let info = loop {
        sender.send_to(&difop, ("127.0.0.1", difop_port)).unwrap();
        if let Ok(info) = driver.get_device_info() {
            break info;
        }
        assert!(
            Instant::now() < deadline,
            "captured DIFOP never enabled DeviceInfo"
        );
        thread::sleep(Duration::from_millis(50));
    };
    let _ = info;
    driver.stop();
}
